---
title: "GPSA Meeting August 23, 2022"
format: revealjs
editor: visual
---

## Agenda {.smaller }


Meeting Agenda - Tuesday, August 23, 2022

- I. Opening remarks
- II. Approve previous minutes
- III. Officers’ Reports (one-two minutes remarks)
- IV. Committee Chairs Reports (one-two minutes remarks)
- V. Presentation on the approach to pay and funding issues (10 minutes remarks)
- VI. Graduate students request to address the GPSA (10 minutes remarks)
- VII. Old business
- VIII. New business

## Officers Reports

- Vice-President
- Administrative Affairs Director
- Financial Director
- Academic Affairs and Advocacy Director
- Student Relations and Communications Director
- Alumni Relations Director

## Committee Reports


- Social Media Committee
- Interdisciplinary Collaborations Committee
- Advocacy Committee
- Events Committee
- Academic and Professional Development Committee
- Communication Committee

## Advocacy Agenda

- Nonmonetary issues
- Nonpay funding issues
- Benefit issues
- Base pay issues
- Inflation issues

## Nonpay funding issues

- GTF tied to TA/RA work
- Estimated Cost of Attendance issues
- Processing of GTFs
- Funding for Master's and Professional Students

## Nonpay, nonbenefit issues

- Largely addressed through Graduate and Professional Studies Committee of Faculty Senate as first stage
- Health insurance costs
- Health insurance quality
- Family and medical leave
- Other benefits - disability, Texas Teacher Retirement system 

## Base Pay Issues

- Existing venue - Graduate Employment Committee
- Minimum pay 
- Biannual raise reviews (existing)
- Additional considerations

## Inflation - Emergency issue

- Graduate Employment Committee has no power to do anything
- Met with Dr. Larsen at 2 PM
- Alternative resources aside from pay - grants, pooled resources (This is not necessarily advocacy; it is just help finding help.)

## Old Business

Covered

## New Business

Questions and short remarks